### PR TITLE
Add GCC 8 and Clang 7

### PR DESCRIPTION
**Pull request by wkaluza**

### CODE REVIEW

**Comment by pbukva** [comment]
CI build SUCCESSFUL.

**Comment by wkaluza** [comment]
The initial reason why I deleted that line was because it wasn't working when I used the dockerfile in the build directly to build the image for testing in Jenkins, as the `/home` directory was empty in that environment. More nebulously, if something does break as a result of this change, this will be a blessing, because it will tell us that we have been building dev images that rely on some config outside of version control, which may only exist on one person's computer. For obvious reasons, this would be a Very Bad Thing.

**Comment by chr15murray** [comment]
It should have worked although it would have been trying to find ./home in whatever folder you executed the build. The home directory mentioned has been in the repo since June last year... https://github.com/uvue-git/docker-images/tree/master/fetch-ledger-develop-image/home

**Comment by wkaluza** [comment]
No, I was getting
```
Step 13/15 : COPY home/* /home/default/
No source files were specified
```

See here for example: https://jenkins.economicagents.com/blue/organizations/jenkins/ledger/detail/PR-1123-merge/21/pipeline/

**Pull request merged**
